### ISSUE TITLE
CW：In some cases 不明确

### ISSUE THREAD

**Issue by VMatrix1900** [simonkorl/draft-moq-for-deadline#11]
> In some cases where the data can be partially accepted, Deadline-aware MoQ Relay MAY cancel some blocks. The relays MAY inform the endpoints and other relays about the drop of these data blocks.

这里的some cases 具体是什么？如果deadline 超了，是确定直接drop，还是要看场景？如果看场景，relay如何判断。

**Comment by simonkorl** [comment]
已修改
