### ISSUE TITLE
passing deadline related information不算action

### ISSUE THREAD

**Issue by VMatrix1900** [simonkorl/draft-moq-for-deadline#12]
> Deadline-aware actions, such as passing deadline-related information from the endpoint to the relay and deadline-aware scheduling on relay nodes will increase the timeliness of data and decrease the cost of bandwidth. 

passing deadline-related information 不能算是actions，是action发生的前置条件，我理解actions只有两个：deadline aware scheduling以及FEC

**Comment by starryskying** [comment]
同意。这部分是否可以描述一下Deadline-aware的整体框架。such as举例的方式难以建立起完整的概念。

**Comment by simonkorl** [comment]
已修改
